### ISSUE TITLE
Current todo list for main devs

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#23]
@georgraess :
- [x] empty-levels branch: insert border / insert segment on empty level
- [x] merge empty-levels branch after completion
- [x] delete point inverse error
- [ ] unit tests
- [ ] more e2e tests 
- [ ] e2e tests firefox

@raphywink :
- [ ] check comments on save
- [ ] dialog css for smaller view (only on element)
- [x] font resize on submenu open/close
- [x] font config for entire app not just canvases
- [x] validate bundle list
